BancoAgSistemas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),

    path('veiculos/', include('veiculo.urls')),
    path('motoristas/', include('motorista.urls')),
    path('controle_veiculos/', include('controle_veiculo.urls')),
]

core/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from django.urls import path

app_name = 'core'

urlpatterns = [
      path('', views.ClassIndexView.as_view(), name='index'),
] + staticfiles_urlpatterns()

motorista/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from django.urls import path

app_name = 'motorista'


urlpatterns = [
      path('', views.MotoristaListView.as_view(), name='list'),
      path('detalhes/<int:pk>/', views.MotoristaDetailView.as_view(), name='detail'),
      path('incluir/', views.MotoristaCreateView.as_view(), name='create'),
      path('atualizar/<int:pk>/', views.MotoristaUpdateView.as_view(), name='update'),
      path('excluir/<int:pk>/', views.MotoristaDeleteView.as_view(), name='delete'),
] + staticfiles_urlpatterns()

motorista/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.basics.models.basic_models import BasicModel


class Motorista(BasicModel):
    cod_motorista = models.CharField(verbose_name=_('Código do motorista'), max_length=50)
    nome = models.CharField(verbose_name=_('Nome'), max_length=300)
    telefone = models.CharField(verbose_name=_('Telefone'), max_length=300, null=True, blank=True)
    cnh = models.CharField(verbose_name=_('Carteira Nacional de Habilitação'), max_length=300, null=True, blank=True)

    class Meta:
        verbose_name = 'Motorista'
        verbose_name_plural = 'Motoristas'
        db_table = 'motorista'

    def __str__(self):
        return f'{self.cod_motorista} - {self.nome}'

    @property
    def telefone_display(self):
        return f'({self.telefone[:2]}) {self.telefone[2:7]}-{self.telefone[7:]}'

motorista/forms.py
from django.forms import ModelForm, forms

from motorista.models import Motorista


class MotoristaForm(ModelForm):
    class Meta:
        model = Motorista
        fields = ('cod_motorista', 'nome', 'telefone', 'cnh',)

    def clean_telefone(self):
        telefone = self.cleaned_data.get('telefone')

        if not telefone.isnumeric():
            raise forms.ValidationError('Informe apenas números ao telefone.')

        if len(telefone) != 11:
            raise forms.ValidationError('Número de telefone inválido')

        return telefone

motorista/views.py
from django.urls import reverse

from core.basics.views import basic_views
from motorista.filters import MotoristaFilter
from motorista.forms import MotoristaForm
from motorista.models import Motorista
from veiculo.forms import VeiculoForm
from veiculo.models import Veiculo


class MotoristaMixin:
    form_class = MotoristaForm
    title = 'Veículos'
    model = Motorista
    template_name = 'menu/base_form.html'

    def get_success_url(self):
        return reverse('motorista:detail', args=[self.object.id])


class MotoristaListView(MotoristaMixin, basic_views.BasicListView):
    filterset_class = MotoristaFilter
    template_name = 'motorista/list.html'


class MotoristaDetailView(MotoristaMixin, basic_views.BasicDetailView):
    template_name = 'motorista/detail.html'

    def get_title_detail(self):
        return f'Detalhes do motorista {self.object.nome}'


class MotoristaCreateView(MotoristaMixin, basic_views.BasicCreateView):
    pass


class MotoristaUpdateView(MotoristaMixin, basic_views.BasicUpdateView):
    pass


class MotoristaDeleteView(MotoristaMixin, basic_views.BasicDeleteView):
    pass

motorista/templates/motorista/detail.html
{% extends 'menu/base.html' %}
{% load static %}

{% block container %}
    <div class="kt-portlet kt-portlet--height-fluid">
        <div class="kt-portlet__head">
            <div class="kt-portlet__head-label">
                <h3 class="kt-portlet__head-title">
                    {{ title_detail|default:'Detalhes' }}
                </h3>
            </div>
            <div class="kt-container--fluid">
                <a href="{% url 'motorista:update' object.id %}" class="btn btn-warning btn-elevate btn-icon-sm"
                   style="margin-top: 10px;">
                    <i class="la la-edit"></i>
                    Editar
                </a>
            </div>
        </div>
        <div class="kt-portlet__body">
        <div class="tab-content">
            <div class="tab-pane active" id="kt_widget5_tab1_content" aria-expanded="true">
                <div class="kt-widget5">
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
<!--                                <img class="kt-widget7__img" src="./assets/media//products/product27.jpg" alt="">-->
                            </div>

                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    {{ object.cod_motorista }} - {{ object.nome }}
                                </a>
                                <p class="kt-widget5__desc">
                                    N° telefone: {{ object.telefone_display }}
                                </p>
                                <div class="kt-widget5__info">
                                    <span>CNH:</span>
                                    <span class="kt-font-info">{{ object.cnh }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number"></span>
                                <span class="kt-widget5__sales"></span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number"></span>
                                <span class="kt-widget5__votes"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="kt_widget5_tab2_content">
                <div class="kt-widget5">
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
                                <img class="kt-widget7__img" src="{% static 'core/assets/media//products/product10.jpg' %}" alt="">
                            </div>
                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    Branding Mockup
                                </a>
                                <p class="kt-widget5__desc">
                                    Metronic bootstrap themes.
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Author:</span>
                                    <span class="kt-font-info">Fly themes</span>
                                    <span>Released:</span>
                                    <span class="kt-font-info">23.08.17</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">24,583</span>
                                <span class="kt-widget5__sales">sales</span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">3809</span>
                                <span class="kt-widget5__votes">votes</span>
                            </div>
                        </div>
                    </div>
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
                                <img class="kt-widget7__img" src="./assets/media//products/product11.jpg" alt="">
                            </div>
                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    Awesome Mobile App
                                </a>
                                <p class="kt-widget5__desc">
                                    Metronic admin themes.Lorem Ipsum Amet
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Author:</span>
                                    <span class="kt-font-info">Fly themes</span>
                                    <span>Released:</span>
                                    <span class="kt-font-info">23.08.17</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">210,054</span>
                                <span class="kt-widget5__sales">sales</span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">1103</span>
                                <span class="kt-widget5__votes">votes</span>
                            </div>
                        </div>
                    </div>
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
                                <img class="kt-widget7__img" src="./assets/media//products/product6.jpg" alt="">
                            </div>
                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    Great Logo Designn
                                </a>
                                <p class="kt-widget5__desc">
                                    Metronic admin themes.
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Author:</span>
                                    <span class="kt-font-info">Keenthemes</span>
                                    <span>Released:</span>
                                    <span class="kt-font-info">23.08.17</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">19,200</span>
                                <span class="kt-widget5__sales">sales</span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">1046</span>
                                <span class="kt-widget5__votes">votes</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="kt_widget5_tab3_content">
                <div class="kt-widget5">i
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
                                <img class="kt-widget7__img" src="./assets/media//products/product11.jpg" alt="">
                            </div>
                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    Awesome Mobile App
                                </a>
                                <p class="kt-widget5__desc">
                                    Metronic admin themes.Lorem Ipsum Amet
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Author:</span>
                                    <span class="kt-font-info">Fly themes</span>
                                    <span>Released:</span>
                                    <span class="kt-font-info">23.08.17</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">210,054</span>
                                <span class="kt-widget5__sales">sales</span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">1103</span>
                                <span class="kt-widget5__votes">votes</span>
                            </div>
                        </div>
                    </div>
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
                                <img class="kt-widget7__img" src="./assets/media//products/product6.jpg" alt="">
                            </div>
                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    Great Logo Designn
                                </a>
                                <p class="kt-widget5__desc">
                                    Metronic admin themes.
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Author:</span>
                                    <span class="kt-font-info">Keenthemes</span>
                                    <span>Released:</span>
                                    <span class="kt-font-info">23.08.17</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">19,200</span>
                                <span class="kt-widget5__sales">sales</span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">1046</span>
                                <span class="kt-widget5__votes">votes</span>
                            </div>
                        </div>
                    </div>
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
                                <img class="kt-widget7__img" src="./assets/media//products/product10.jpg" alt="">
                            </div>
                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    Branding Mockup
                                </a>
                                <p class="kt-widget5__desc">
                                    Metronic bootstrap themes.
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Author:</span>
                                    <span class="kt-font-info">Fly themes</span>
                                    <span>Released:</span>
                                    <span class="kt-font-info">23.08.17</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">24,583</span>
                                <span class="kt-widget5__sales">sales</span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">3809</span>
                                <span class="kt-widget5__votes">votes</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

motorista/templates/motorista/list.html
{% extends 'menu/base_list.html' %}

{% block table_actions %}
    <a href="{% url 'motorista:create' %}" class="btn btn-brand btn-elevate btn-icon-sm">
        <i class="la la-plus"></i>
        Novo Motorista
    </a>
{% endblock %}

{% block grid_header %}
    <th class="text-center">
        <span>Cód. do Motorista</span>
    </th>
    <th class="text-center">
        <span>Nome</span>
    </th>
    <th class="text-center">
        <span>Telefone</span>
    </th>
    <th class="text-center">
        <span>CNH</span>
    </th>
    <th class="text-center">
        <span>Ações</span>
    </th>
{% endblock %}

{% block grid_item %}
    <td class="text-center">{{ item.cod_motorista }}</td>
    <td class="text-center">{{ item.nome }}</td>
    <td class="text-center">{{ item.telefone }}</td>
    <td class="text-center">{{ item.cnh }}</td>
    <td class="text-center">
        <a href="{% url 'motorista:detail' item.id %}" class="btn btn-success btn-elevate btn-icon-sm"
            data-toggle="kt-tooltip" data-original-title="Visualizar"
        >
            <i class="la la-book"></i>
        </a>
        <a href="{% url 'motorista:update' item.id %}" class="btn btn-warning btn-elevate btn-icon-sm"
            data-toggle="kt-tooltip" data-original-title="Editar"
        >
            <i class="la la-edit"></i>
        </a>

        <a href="#" class="btn btn-danger btn-elevate btn-icon-sm btn_action_delete"
           url="{% url 'motorista:delete' item.id %}"
           descricao="{{ item.nome }}"
           data-toggle="kt-tooltip" data-original-title="Excluir registro"
        >
            <i class="la la-trash"></i>
        </a>
    </td>
{% endblock %}