BancoAgSistemas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),

    path('veiculos/', include('veiculo.urls')),
    path('motoristas/', include('motorista.urls')),
    path('controle_veiculos/', include('controle_veiculo.urls')),
]

controle_veiculo/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from django.urls import path

app_name = 'controle-veiculo'

urlpatterns = [
      path('', views.ControleVeiculoListView.as_view(), name='list'),
      path('detalhes/<int:pk>/', views.ControleVeiculoDetailView.as_view(), name='detail'),
      path('incluir/', views.ControleVeiculoCreateView.as_view(), name='create'),
      path('atualizar/<int:pk>/', views.ControleVeiculoUpdateView.as_view(), name='update'),
      path('excluir/<int:pk>/', views.ControleVeiculoDeleteView.as_view(), name='delete'),
] + staticfiles_urlpatterns()

core/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from django.urls import path

app_name = 'core'

urlpatterns = [
      path('', views.ClassIndexView.as_view(), name='index'),
] + staticfiles_urlpatterns()

controle_veiculo/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from controle_veiculo.business import ControleVeiculoBusiness
from core.basics.business.basic_business import BaseModelBusiness
from core.basics.models.basic_models import BasicModel


class ControleVeiculo(BaseModelBusiness, BasicModel):
    veiculo = models.ForeignKey(
        'veiculo.Veiculo', verbose_name=_('Veículo'), related_name='controles', on_delete=models.CASCADE
    )
    motorista = models.ForeignKey(
        'motorista.Motorista', verbose_name=_('Motorista'), related_name='controles', on_delete=models.CASCADE
    )

    data_saida = models.DateField(verbose_name=_('Data da saída'))
    hora_saida = models.TimeField(verbose_name=_('Hora da saída'))
    km_saida = models.DecimalField(verbose_name=_('Km da saída'), max_digits=10, decimal_places=2)

    destino = models.CharField(verbose_name=_('Destino'), max_length=300, null=True, blank=True)

    data_retorno = models.DateField(verbose_name=_('Data do retorno'), null=True, blank=True)
    hora_retorno = models.TimeField(verbose_name=_('Hora da chegada'), null=True, blank=True)
    km_retorno = models.DecimalField(
        verbose_name=_('Km da volta'), max_digits=10, decimal_places=2, null=True, blank=True
    )

    km_percorrido = models.DecimalField(
        verbose_name=_('Km percorridos'), max_digits=10, decimal_places=2, null=True, blank=True
    )

    business_class = ControleVeiculoBusiness

    class Meta:
        verbose_name = 'Controle do veículo'
        verbose_name_plural = 'Controle dos veículos'
        db_table = 'controle'

    def __str__(self):
        return f'{self.veiculo} - {self.motorista}'

    def save(self, *args, **kwargs):
        if not self.km_percorrido:
            if self.km_saida and self.km_retorno:
                self.km_percorrido = self.km_retorno - self.km_saida

        super().save(args, **kwargs)

controle_veiculo/forms.py
from django.forms import ModelForm
from django import forms

from .models import ControleVeiculo


class ControleForm(ModelForm):

    class Meta:
        model = ControleVeiculo
        fields = (
            'veiculo', 'motorista', 'data_saida', 'hora_saida', 'km_saida', 'destino', 'data_retorno', 'hora_retorno',
            'km_retorno', 'km_percorrido'
        )

        widgets = {
            'data_saida': forms.DateInput(format='%Y-%m-%d', attrs={'class': 'form-control', 'type': 'date'}),
            'hora_saida': forms.TimeInput(format='%Y-%m-%d', attrs={'class': 'form-control', 'type': 'time'}),

            'data_retorno': forms.DateInput(format='%Y-%m-%d', attrs={'class': 'form-control', 'type': 'date'}),
            'hora_retorno': forms.TimeInput(format='%Y-%m-%d', attrs={'class': 'form-control', 'type': 'time'}),
        }

    def clean_km_retorno(self):
        km_retorno = self.cleaned_data.get('km_retorno')
        km_saida = self.cleaned_data.get('km_saida')

        if km_retorno < km_saida:
            raise forms.ValidationError('Km de retorno não pode ser menor que o da saída.')

        return km_retorno

controle_veiculo/views.py
from django.urls import reverse

from controle_veiculo.filters import ControleVeiculoFilter
from controle_veiculo.forms import ControleForm
from controle_veiculo.models import ControleVeiculo
from core.basics.views import basic_views


class ControleVeiculoMixin:
    form_class = ControleForm
    title = 'Controles dos Veículos'
    model = ControleVeiculo
    template_name = 'menu/base_form.html'

    def get_success_url(self):
        return reverse('controle-veiculo:detail', args=[self.object.id])


class ControleVeiculoListView(ControleVeiculoMixin, basic_views.BasicListView):
    template_name = 'controle_veiculo/list.html'
    filterset_class = ControleVeiculoFilter

    def get_queryset(self):
        return ControleVeiculo.objects.select_related('veiculo', 'motorista').order_by('-data_saida')


class ControleVeiculoDetailView(ControleVeiculoMixin, basic_views.BasicDetailView):
    template_name = 'controle_veiculo/detail.html'

    def get_title_detail(self):
        return f'Detalhes do veículo {self.object.veiculo}'


class ControleVeiculoCreateView(ControleVeiculoMixin, basic_views.BasicCreateView):

    def do_create(self, form):
        super().do_create(form)
        self.object.business.atualizar_km_ate_proxima_troca()


class ControleVeiculoUpdateView(ControleVeiculoMixin, basic_views.BasicUpdateView):

    def do_update(self, form):
        super().do_update(form)
        self.object.business.atualizar_km_ate_proxima_troca()


class ControleVeiculoDeleteView(ControleVeiculoMixin, basic_views.BasicDeleteView):
    pass

controle_veiculo/templates/controle_veiculo/detail.html
{% extends 'menu/base_detail.html' %}
{% load static %}

{% block container %}
    <div class="kt-portlet kt-portlet--height-fluid">
        <div class="kt-portlet__head">
            <div class="kt-portlet__head-label">
                <h3 class="kt-portlet__head-title">
                    {{ title_detail|default:'Detalhes' }}
                </h3>
            </div>
            <div class="kt-container--fluid">
                <a href="{% url 'controle-veiculo:update' object.id %}" class="btn btn-warning btn-elevate btn-icon-sm"
                   style="margin-top: 10px;">
                    <i class="la la-edit"></i>
                    Editar
                </a>
            </div>
        </div>
        <div class="kt-portlet__body">
            <div class="tab-content">
                <div class="tab-pane active" id="kt_widget5_tab1_content" aria-expanded="true">
                    <div class="kt-widget5">
                        <div class="kt-widget5__item">
                            <div class="kt-widget5__content">
                                <div class="kt-widget5__pic">
                                </div>

                                <div class="kt-widget5__section">
                                    <a href="#" class="kt-widget5__title">
                                        Veiculo: {{ object.veiculo }}
                                    </a>
                                    <p class="kt-widget5__desc">
                                        Motorista responsável: {{ object.motorista.nome }}
                                    </p>
                                    <div class="kt-widget5__info">
                                        <span>Km percorridos:</span>
                                        <span class="kt-font-info">{{ object.km_percorrido }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="kt-widget5__content">
                                <div class="kt-widget5__stats">
                                    <span class="kt-widget5__number">Data Prevista para entrega</span>
                                    <span class="kt-widget5__sales">{{ object.data_retorno }} as {{ object.hora_retorno }}</span>
                                </div>
                                <div class="kt-widget5__stats">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

controle_veiculo/templates/controle_veiculo/list.html
{% extends 'menu/base_list.html' %}

{% block table_actions %}
    <a href="{% url 'controle-veiculo:create' %}" class="btn btn-brand btn-elevate btn-icon-sm">
        <i class="la la-plus"></i>
        Novo Controle de Veículo
    </a>
{% endblock %}

{% block search %}
    <div class="col-lg-9 col-xl-8">
        <div class="row align-items-center">
            <div class="col-md-4 my-2 my-md-0">
                <div class="input-icon">
                    <input type="text" class="form-control" name="search" placeholder="Buscar por..." id="search-query">
                    <span><i class="flaticon2-search-1 text-muted"></i></span>
                </div>
            </div>
            <a href="#" class="btn btn-brand btn-elevate btn-icon-sm">
                Search
            </a>
            <div class="col-md-3" style="padding-right: 0;">
                <div class="kt-widget__details">
                    <input type="date" name="data" class="form-control" id="id-data">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block grid_header %}
    <th class="text-center">
        <span>Veiculo</span>
    </th>
    <th class="text-center">
        <span>Motorista</span>
    </th>

    <th class="text-center">
        <span>Data de saída</span>
    </th>
    <th class="text-center">
        <span>Data prevista para chegada</span>
    </th>
    <th class="text-center">
        <span>Ações</span>
    </th>
{% endblock %}

{% block grid_item %}
    <td class="text-center">{{ item.veiculo }}</td>
    <td class="text-center">{{ item.motorista }}</td>
    <td class="text-center">{{ item.data_saida }} as {{ item.hora_saída }}</td>
    <td class="text-center">{{ item.data_retorno }} as {{ item.hora_retorno }}</td>

    <td class="text-center">
        <a href="{% url 'controle-veiculo:detail' item.id %}" class="btn btn-success btn-elevate btn-icon-sm"
            data-toggle="kt-tooltip" data-original-title="Visualizar"
        >
            <i class="la la-book"></i>
        </a>
        <a href="{% url 'controle-veiculo:update' item.id %}" class="btn btn-warning btn-elevate btn-icon-sm"
            data-toggle="kt-tooltip" data-original-title="Editar"
        >
            <i class="la la-edit"></i>
        </a>

        <a href="#" class="btn btn-danger btn-elevate btn-icon-sm btn_action_delete"
           url="{% url 'controle-veiculo:delete' item.id %}"
           descricao="{{ item.veiculo }}"
           data-toggle="kt-tooltip" data-original-title="Excluir registro"
        >
            <i class="la la-trash"></i>
        </a>
    </td>
{% endblock %}

{% block script %}
    {{ block.super }}

    <script>
        $(document).ready(function () {
            $('#id-data').on('change', function () {
                var data = $('#id-data').val()
                if (data.slice(0, 4) > 1990) $('#form-search').submit();
            })
        })
    </script>
{% endblock %}