BancoAgSistemas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),

    path('veiculos/', include('veiculo.urls')),
    path('motoristas/', include('motorista.urls')),
    path('controle_veiculos/', include('controle_veiculo.urls')),
]

core/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from django.urls import path

app_name = 'core'

urlpatterns = [
      path('', views.ClassIndexView.as_view(), name='index'),
] + staticfiles_urlpatterns()

veiculo/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from django.urls import path

app_name = 'veiculo'

urlpatterns = [
      path('', views.VeiculoListView.as_view(), name='list'),
      path('detalhes/<int:pk>/', views.VeiculoDetailView.as_view(), name='detail'),
      path('incluir/', views.VeiculoCreateView.as_view(), name='create'),
      path('atualizar/<int:pk>/', views.VeiculoUpdateView.as_view(), name='update'),
      path('excluir/<int:pk>/', views.VeiculoDeleteView.as_view(), name='delete'),
] + staticfiles_urlpatterns()

veiculo/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.basics.models.basic_models import BasicModel


class Veiculo(BasicModel):
    placa = models.CharField(verbose_name=_('Placa'), max_length=7)
    marca = models.CharField(verbose_name=_('Marca'), max_length=100)
    veiculo = models.TextField(verbose_name=_('Veículo'))
    km_troca_oleo = models.DecimalField(
        verbose_name=_('Quilometros até a próxima troca'), default=0, max_digits=10, decimal_places=2
    )

    class Meta:
        verbose_name = 'Veículo'
        verbose_name_plural = 'Veículos'
        db_table = 'veiculo'

    def __str__(self):
        return f'{self.marca} - {self.placa}'

veiculo/forms.py
from django.forms import ModelForm, forms

from veiculo.models import Veiculo


class VeiculoForm(ModelForm):
    class Meta:
        model = Veiculo
        fields = ('placa', 'marca', 'veiculo', 'km_troca_oleo')

    def clean_placa(self):
        placa = self.cleaned_data.get('placa')
        veiculos = Veiculo.objects.filter(placa=placa).exclude(id=self.instance.id)

        if veiculos.exists():
            raise forms.ValidationError('Já existem veículos cadastrados com essa mesma placa.')

        return placa

veiculo/views.py
from django.urls import reverse

from core.basics.views import basic_views
from core.basics.views.basic_alerts import BasicModelAlertViewMixin
from veiculo.alerts import VeiculoAlert
from veiculo.filters import VeiculoFilter
from veiculo.forms import VeiculoForm
from veiculo.models import Veiculo


class VeiculoMixin:
    form_class = VeiculoForm
    title = 'Veículos'
    model = Veiculo
    template_name = 'menu/base_form.html'

    def get_success_url(self):
        return reverse('veiculo:detail', args=[self.object.id])


class VeiculoListView(VeiculoMixin, basic_views.BasicListView):
    filterset_class = VeiculoFilter
    template_name = 'veiculo/list.html'


class VeiculoDetailView(VeiculoMixin, BasicModelAlertViewMixin, basic_views.BasicDetailView):
    alert_class = VeiculoAlert
    template_name = 'veiculo/detail.html'

    def get_title_detail(self):
        return f'Detalhes do veículo {self.object.veiculo}'


class VeiculoCreateView(VeiculoMixin, basic_views.BasicCreateView):
    pass


class VeiculoUpdateView(VeiculoMixin, basic_views.BasicUpdateView):
    pass


class VeiculoDeleteView(VeiculoMixin, basic_views.BasicDeleteView):
    pass

veiculo/templates/veiculo/detail.html
{% extends 'menu/base.html' %}
{% load static %}

{% block container %}
    <div class="kt-portlet kt-portlet--height-fluid">
        <div class="kt-portlet__head">
            <div class="kt-portlet__head-label">
                <h3 class="kt-portlet__head-title">
                    {{ title_detail|default:'Detalhes' }}
                </h3>
            </div>
            <div class="kt-container--fluid">
                <a href="{% url 'veiculo:update' object.id %}" class="btn btn-warning btn-elevate btn-icon-sm"
                   style="margin-top: 10px;">
                    <i class="la la-edit"></i>
                    Editar
                </a>
            </div>
        </div>
        <div class="kt-portlet__body">
        <div class="tab-content">
            <div class="tab-pane active" id="kt_widget5_tab1_content" aria-expanded="true">
                <div class="kt-widget5">
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
<!--                                <img class="kt-widget7__img" src="./assets/media//products/product27.jpg" alt="">-->
                            </div>

                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    {{ object.placa }} - {{ object.veiculo }}
                                </a>
                                <p class="kt-widget5__desc">
                                    {{ object.marca }}
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Km até a próxima troca:</span>
                                    <span class="kt-font-info">{{ object.km_troca_oleo }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
<!--                                <span class="kt-widget5__number">19,200</span>-->
<!--                                <span class="kt-widget5__sales">sales</span>-->
                            </div>
                            <div class="kt-widget5__stats">
<!--                                <span class="kt-widget5__number">1046</span>-->
<!--                                <span class="kt-widget5__votes">votes</span>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="kt_widget5_tab2_content">
                <div class="kt-widget5">
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
                                <img class="kt-widget7__img" src="{% static 'core/assets/media//products/product10.jpg' %}" alt="">
                            </div>
                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    Branding Mockup
                                </a>
                                <p class="kt-widget5__desc">
                                    Metronic bootstrap themes.
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Author:</span>
                                    <span class="kt-font-info">Fly themes</span>
                                    <span>Released:</span>
                                    <span class="kt-font-info">23.08.17</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">24,583</span>
                                <span class="kt-widget5__sales">sales</span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">3809</span>
                                <span class="kt-widget5__votes">votes</span>
                            </div>
                        </div>
                    </div>
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
                                <img class="kt-widget7__img" src="./assets/media//products/product11.jpg" alt="">
                            </div>
                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    Awesome Mobile App
                                </a>
                                <p class="kt-widget5__desc">
                                    Metronic admin themes.Lorem Ipsum Amet
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Author:</span>
                                    <span class="kt-font-info">Fly themes</span>
                                    <span>Released:</span>
                                    <span class="kt-font-info">23.08.17</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">210,054</span>
                                <span class="kt-widget5__sales">sales</span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">1103</span>
                                <span class="kt-widget5__votes">votes</span>
                            </div>
                        </div>
                    </div>
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
                                <img class="kt-widget7__img" src="./assets/media//products/product6.jpg" alt="">
                            </div>
                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    Great Logo Designn
                                </a>
                                <p class="kt-widget5__desc">
                                    Metronic admin themes.
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Author:</span>
                                    <span class="kt-font-info">Keenthemes</span>
                                    <span>Released:</span>
                                    <span class="kt-font-info">23.08.17</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">19,200</span>
                                <span class="kt-widget5__sales">sales</span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">1046</span>
                                <span class="kt-widget5__votes">votes</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="kt_widget5_tab3_content">
                <div class="kt-widget5">i
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
                                <img class="kt-widget7__img" src="./assets/media//products/product11.jpg" alt="">
                            </div>
                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    Awesome Mobile App
                                </a>
                                <p class="kt-widget5__desc">
                                    Metronic admin themes.Lorem Ipsum Amet
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Author:</span>
                                    <span class="kt-font-info">Fly themes</span>
                                    <span>Released:</span>
                                    <span class="kt-font-info">23.08.17</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">210,054</span>
                                <span class="kt-widget5__sales">sales</span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">1103</span>
                                <span class="kt-widget5__votes">votes</span>
                            </div>
                        </div>
                    </div>
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
                                <img class="kt-widget7__img" src="./assets/media//products/product6.jpg" alt="">
                            </div>
                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    Great Logo Designn
                                </a>
                                <p class="kt-widget5__desc">
                                    Metronic admin themes.
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Author:</span>
                                    <span class="kt-font-info">Keenthemes</span>
                                    <span>Released:</span>
                                    <span class="kt-font-info">23.08.17</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">19,200</span>
                                <span class="kt-widget5__sales">sales</span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">1046</span>
                                <span class="kt-widget5__votes">votes</span>
                            </div>
                        </div>
                    </div>
                    <div class="kt-widget5__item">
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__pic">
                                <img class="kt-widget7__img" src="./assets/media//products/product10.jpg" alt="">
                            </div>
                            <div class="kt-widget5__section">
                                <a href="#" class="kt-widget5__title">
                                    Branding Mockup
                                </a>
                                <p class="kt-widget5__desc">
                                    Metronic bootstrap themes.
                                </p>
                                <div class="kt-widget5__info">
                                    <span>Author:</span>
                                    <span class="kt-font-info">Fly themes</span>
                                    <span>Released:</span>
                                    <span class="kt-font-info">23.08.17</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget5__content">
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">24,583</span>
                                <span class="kt-widget5__sales">sales</span>
                            </div>
                            <div class="kt-widget5__stats">
                                <span class="kt-widget5__number">3809</span>
                                <span class="kt-widget5__votes">votes</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

veiculo/templates/veiculo/list.html
{% extends 'menu/base_list.html' %}

{% block table_actions %}
    <a href="{% url 'veiculo:create' %}" class="btn btn-brand btn-elevate btn-icon-sm">
        <i class="la la-plus"></i>
        Novo veículo
    </a>
{% endblock %}

{% block grid_header %}
    <th class="text-center">
        <span>N° placa</span>
    </th>
    <th class="text-center">
        <span>Marca</span>
    </th>
    <th class="text-center">
        <span>Veículo</span>
    </th>
    <th class="text-center">
        <span>Quilometros até a próx. troca</span>
    </th>
    <th class="text-center">
        <span>Ações</span>
    </th>
{% endblock %}

{% block grid_item %}
    <td class="text-center">{{ item.placa }}</td>
    <td class="text-center">{{ item.marca }}</td>
    <td class="text-center">{{ item.veiculo }}</td>
    <td class="text-center">{{ item.km_troca_oleo }}</td>
    <td class="text-center">
        <a href="{% url 'veiculo:detail' item.id %}" class="btn btn-success btn-elevate btn-icon-sm"
            data-toggle="kt-tooltip" data-original-title="Visualizar"
        >
            <i class="la la-book"></i>
        </a>
        <a href="{% url 'veiculo:update' item.id %}" class="btn btn-warning btn-elevate btn-icon-sm"
            data-toggle="kt-tooltip" data-original-title="Editar"
        >
            <i class="la la-edit"></i>
        </a>

        <a href="#" class="btn btn-danger btn-elevate btn-icon-sm btn_action_delete"
           url="{% url 'veiculo:delete' item.id %}"
           descricao="{{ item.veiculo }}"
           data-toggle="kt-tooltip" data-original-title="Excluir registro"
        >
            <i class="la la-trash"></i>
        </a>
    </td>
{% endblock %}